# Generated by Django 5.1.15 on 2026-10-02 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('administration', '0001_initial'),
        ('calendar_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical / Urgent'), ('SUCCESS', 'Success')], default='INFO', max_length=16)),
                ('category', models.CharField(choices=[('PAYMENT_DUE', 'Upcoming Payment Due'), ('PAYMENT_OVERDUE', 'Overdue Payment'), ('CONTRACT_RENEWAL', 'Contract Renewal'), ('CONSIGNMENT_DELIVERY', 'Consignment Delivery'), ('STOCK_ALERT', 'Low Stock Alert'), ('DOCUMENT_PROCESSED', 'Document Analyzed'), ('GENERAL', 'General Alert')], default='GENERAL', max_length=32)),
                ('action_url', models.CharField(blank=True, max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('related_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='administration.contract')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounting.invoice')),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='calendar_tasks.calendartask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
