# Generated by Django 5.1.15 on 2026-10-02 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(default='application/pdf', max_length=128)),
                ('document_type', models.CharField(choices=[('INVOICE_PAYABLE', 'Vendor Invoice (Payable)'), ('INVOICE_RECEIVABLE', 'Customer Invoice (Receivable)'), ('CONTRACT', 'Contract / Agreement'), ('CONSIGNMENT', 'Consignment / Delivery Note'), ('RECEIPT', 'Receipt / Expense Voucher'), ('UNKNOWN', 'General / Unclassified')], default='UNKNOWN', max_length=32)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing with AI'), ('READY_FOR_REVIEW', 'Ready for Review'), ('CONFIRMED', 'Confirmed & Synced'), ('FAILED', 'Processing Failed')], default='UPLOADED', max_length=32)),
                ('raw_ai_response', models.JSONField(blank=True, default=dict)),
                ('verified_data', models.JSONField(blank=True, default=dict)),
                ('extraction_error', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(default=1)),
                ('page_image', models.ImageField(blank=True, null=True, upload_to='documents/pages/%Y/%m/')),
                ('extracted_text', models.TextField(blank=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.document')),
            ],
            options={
                'ordering': ['document', 'page_number'],
                'unique_together': {('document', 'page_number')},
            },
        ),
    ]
