# Generated by Django 5.1.15 on 2026-10-02 17:42

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('administration', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=64, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('unit_of_measure', models.CharField(default='pcs', max_length=32)),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('quantity_on_hand', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('reorder_threshold', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=12)),
                ('location', models.CharField(blank=True, help_text='Warehouse shelf/bin location', max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Consignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_number', models.CharField(db_index=True, help_text='Waybill or Consignment Note No.', max_length=128)),
                ('direction', models.CharField(choices=[('INWARD', 'Inward Receipt (Supplier Delivery)'), ('OUTWARD', 'Outward Dispatch (Customer Delivery)')], default='INWARD', max_length=16)),
                ('delivery_date', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('carrier', models.CharField(blank=True, max_length=128)),
                ('tracking_number', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('EXPECTED', 'Expected / In Transit'), ('RECEIVED_CONFIRMED', 'Received & Stocked'), ('DISCREPANCY', 'Discrepancy Noted'), ('REJECTED', 'Rejected')], default='EXPECTED', max_length=32)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignments', to='administration.counterparty')),
                ('linked_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignments', to='accounting.invoice')),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_consignments', to='documents.document')),
            ],
            options={
                'ordering': ['-delivery_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsignmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_expected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('consignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.consignment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consignment_items', to='warehouse.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('PURCHASE_RECEIPT', 'Purchase Receipt / Inward'), ('SALES_SHIPMENT', 'Sales Shipment / Outward'), ('INVENTORY_ADJUSTMENT', 'Stock Count / Adjustment'), ('RETURN', 'Return to Supplier / Customer Return')], max_length=32)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positive for additions, negative for reductions', max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=128)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('consignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='warehouse.consignment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='warehouse.product')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
