# Generated by Django 5.1.15 on 2026-10-02 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('counterparty_type', models.CharField(choices=[('VENDOR', 'Vendor / Supplier'), ('CUSTOMER', 'Customer / Client'), ('PARTNER', 'Business Partner'), ('CARRIER', 'Logistics / Carrier'), ('FINANCIAL', 'Bank / Financial Institution')], default='VENDOR', max_length=20)),
                ('tax_id', models.CharField(blank=True, help_text='Tax / VAT / EIN Number', max_length=64)),
                ('registration_number', models.CharField(blank=True, help_text='Company Registry No.', max_length=64)),
                ('iban', models.CharField(blank=True, help_text='Bank Account IBAN', max_length=64)),
                ('bank_name', models.CharField(blank=True, max_length=128)),
                ('swift_bic', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('address', models.TextField(blank=True)),
                ('default_payment_terms_days', models.PositiveIntegerField(default=14, help_text='Standard payment terms in days (e.g. 14, 30)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Counterparty',
                'verbose_name_plural': 'Counterparties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contract_number', models.CharField(blank=True, db_index=True, max_length=128)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, help_text='Expiration or renewal deadline', null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('renewal_notice_period_days', models.PositiveIntegerField(default=30, help_text='Days before expiration to take renewal decision')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PENDING_RENEWAL', 'Pending Renewal'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('key_terms_summary', models.TextField(blank=True, help_text='AI or user summarized terms and clauses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_contracts', to='documents.document')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='administration.counterparty')),
            ],
            options={
                'ordering': ['-end_date', '-created_at'],
            },
        ),
    ]
