# Generated by Django 5.1.15 on 2026-10-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(default='Acme Operations Ltd', help_text='Official registered corporate name', max_length=255, verbose_name='Legal Entity Name')),
                ('trade_name', models.CharField(blank=True, default='Acme Operations', help_text='Public-facing business name if different from legal name', max_length=255, verbose_name='Trade / Commercial Name')),
                ('tax_id', models.CharField(blank=True, default='DE318492019', help_text='VAT number, EIN, or national tax identifier', max_length=64, verbose_name='Tax / VAT ID')),
                ('registration_number', models.CharField(blank=True, help_text='Commercial register number / CRN', max_length=64, verbose_name='Company Registry No.')),
                ('iban', models.CharField(blank=True, default='DE89370400440532013000', help_text='Default bank account for receiving customer payments', max_length=64, verbose_name='Primary Bank IBAN')),
                ('bank_name', models.CharField(blank=True, default='Deutsche Bank AG', max_length=128, verbose_name='Bank Name')),
                ('swift_bic', models.CharField(blank=True, default='DEUTDEDDFXX', max_length=32, verbose_name='SWIFT / BIC Code')),
                ('email', models.EmailField(blank=True, default='finance@acme-ops.de', max_length=254, verbose_name='Accounting / Finance Email')),
                ('phone', models.CharField(blank=True, default='+49 30 554321', max_length=64, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, default='Friedrichstrasse 120, 10117 Berlin, Germany', verbose_name='Registered Address')),
                ('currency', models.CharField(default='EUR', help_text='Base currency code (e.g. EUR, USD, GBP)', max_length=8, verbose_name='Functional Currency')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
    ]
