# Generated by Django 5.1.15 on 2026-10-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI / ChatGPT'), ('claude', 'Anthropic Claude'), ('deepseek', 'DeepSeek'), ('qwen', 'Alibaba Qwen (通义千问)'), ('custom', 'Custom / Local (Ollama)')], default='gemini', help_text='Currently active AI model provider.', max_length=32)),
                ('gemini_api_key', models.CharField(blank=True, max_length=255)),
                ('gemini_model', models.CharField(blank=True, default='gemini-2.5-flash', max_length=64)),
                ('openai_api_key', models.CharField(blank=True, max_length=255)),
                ('openai_model', models.CharField(blank=True, default='gpt-4o', max_length=64)),
                ('openai_base_url', models.CharField(blank=True, default='https://api.openai.com/v1', max_length=255)),
                ('claude_api_key', models.CharField(blank=True, max_length=255)),
                ('claude_model', models.CharField(blank=True, default='claude-3-7-sonnet-20250219', max_length=64)),
                ('claude_base_url', models.CharField(blank=True, default='https://api.anthropic.com', max_length=255)),
                ('deepseek_api_key', models.CharField(blank=True, max_length=255)),
                ('deepseek_model', models.CharField(blank=True, default='deepseek-chat', max_length=64)),
                ('deepseek_base_url', models.CharField(blank=True, default='https://api.deepseek.com', max_length=255)),
                ('qwen_api_key', models.CharField(blank=True, max_length=255)),
                ('qwen_model', models.CharField(blank=True, default='qwen-plus', max_length=64)),
                ('qwen_base_url', models.CharField(blank=True, default='https://dashscope-intl.aliyuncs.com/compatible-mode/v1', max_length=255)),
                ('custom_api_key', models.CharField(blank=True, max_length=255)),
                ('custom_model', models.CharField(blank=True, default='llama3.3', max_length=64)),
                ('custom_base_url', models.CharField(blank=True, default='http://localhost:11434/v1', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
            },
        ),
    ]
